class ValidatorError(Exception): ...


class TaskDefinitionError(ValidatorError): ...


class TaskCreationError(ValidatorError): ...


class OpenAIClientError(ValidatorError): ...


class OpenAIInternalError(ValidatorError): ...
